# Generated by Django 6.0.7 on 2026-07-20 14:46

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('original_url', models.URLField(help_text='The destination URL.', verbose_name='Original URL')),
                ('target_domain', models.CharField(db_index=True, editable=False, help_text='Extracted domain from the original URL.', max_length=255)),
                ('short_code', models.CharField(db_index=True, editable=False, help_text='Unique short code.', max_length=8, unique=True)),
                ('click_count', models.PositiveIntegerField(default=0, help_text='Total number of successful redirects.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_clicked_at', models.DateTimeField(blank=True, help_text='Most recent successful redirect.', null=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='HistoricalShortURL',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('original_url', models.URLField(help_text='The destination URL.', verbose_name='Original URL')),
                ('target_domain', models.CharField(db_index=True, editable=False, help_text='Extracted domain from the original URL.', max_length=255)),
                ('short_code', models.CharField(db_index=True, editable=False, help_text='Unique short code.', max_length=8)),
                ('click_count', models.PositiveIntegerField(default=0, help_text='Total number of successful redirects.')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('last_clicked_at', models.DateTimeField(blank=True, help_text='Most recent successful redirect.', null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical short url',
                'verbose_name_plural': 'historical short urls',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalClickEvent',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('clicked_at', models.DateTimeField(blank=True, db_index=True, editable=False, help_text='When the redirect happened.')),
                ('browser', models.CharField(blank=True, help_text='Detected browser name.', max_length=100, null=True)),
                ('operating_system', models.CharField(blank=True, help_text='Detected operating system.', max_length=100, null=True)),
                ('device_type', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet'), ('bot', 'Bot'), ('unknown', 'Unknown')], default='unknown', help_text='Detected device type.', max_length=20)),
                ('country', models.CharField(blank=True, help_text='Detected visitor country.', max_length=100, null=True)),
                ('referer', models.URLField(blank=True, help_text='HTTP Referer header, if present.', max_length=500, null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Raw User-Agent header.', null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('short_url', models.ForeignKey(blank=True, db_constraint=False, help_text='The shortened URL that was accessed.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.shorturl')),
            ],
            options={
                'verbose_name': 'historical click event',
                'verbose_name_plural': 'historical click events',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ClickEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('clicked_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the redirect happened.')),
                ('browser', models.CharField(blank=True, help_text='Detected browser name.', max_length=100, null=True)),
                ('operating_system', models.CharField(blank=True, help_text='Detected operating system.', max_length=100, null=True)),
                ('device_type', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet'), ('bot', 'Bot'), ('unknown', 'Unknown')], default='unknown', help_text='Detected device type.', max_length=20)),
                ('country', models.CharField(blank=True, help_text='Detected visitor country.', max_length=100, null=True)),
                ('referer', models.URLField(blank=True, help_text='HTTP Referer header, if present.', max_length=500, null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Raw User-Agent header.', null=True)),
                ('short_url', models.ForeignKey(help_text='The shortened URL that was accessed.', on_delete=django.db.models.deletion.CASCADE, related_name='click_events', to='app.shorturl')),
            ],
            options={
                'ordering': ('-clicked_at',),
            },
        ),
    ]
