# Generated by Django 6.0.7 on 2026-07-23 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalshorturl',
            name='original_url',
            field=models.URLField(help_text='The destination URL.', max_length=2048, verbose_name='Original URL'),
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='original_url',
            field=models.URLField(help_text='The destination URL.', max_length=2048, verbose_name='Original URL'),
        ),
    ]
